# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.5
  - nightly

notifications:
  email: false

addons:
  apt:
    packages:
    - telnet
    - openvpn
    update: true
  homebrew:
    packages:
    - telnet
    update: true

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install telnet -y; fi

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly
  - os: linux
  - os: windows

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
